CREATE TABLE [dbo].[STG_NBA_Season_Stats_1950_2017](
            [season][numeric](4,0) NULL,
            [player][nvarchar](20) NULL,
			[position][nvarchar](3) NULL,
			[age][numeric](2,0) NULL,
			[team][nvarchar](5) NULL,
            [GP][numeric](8,0) NULL,
			[PTS][numeric](8,0) NULL,
			[MIN][numeric](8,0) NULL,
			[FGM][numeric](8,0) NULL,
			[FGA][numeric](8,0) NULL,
			[FG%][numeric](8,0) NULL,
			[3PM][numeric](8,0) NULL,
			[3PA][numeric](8,0) NULL,
			[3P%][numeric](8,0) NULL,
			[2PM][numeric](8,0) NULL,
			[2PA][numeric](8,0) NULL,
			[2P%][numeric](8,0) NULL,
			[FTM][numeric](8,0) NULL,
			[FTA][numeric](8,0) NULL,
			[FT%][numeric](8,0) NULL,
			[eFG%][numeric](8,0) NULL,
			[OREB][numeric](8,0) NULL,
			[DREB][numeric](8,0) NULL,
			[REB][numeric](8,0) NULL,
			[AST][numeric](8,0) NULL,
			[TOV][numeric](8,0) NULL,
			[STL][numeric](8,0) NULL,
			[BLK][numeric](8,0) NULL,
			[PF][numeric](8,0) NULL,
			[EFF][numeric](8,0) NULL,
) ON [PRIMARY]
GO