CREATE TABLE [dbo].[STG_NBA_PLAYERS](
            [pk_jugador][numeric](4,0) NULL,
			[liga][varchar](5) NULL,
			[cod_jugador][varchar](100) NULL,
			[nombre][varchar](255) NULL,
			[posicion_juego][varchar](100) NULL,
			[sexo][numeric](4,0) NULL,
			[activo][varchar](10) NULL,
			[altura][varchar](50) NULL,
			[peso][varchar](50) NULL,
			[shoots][varchar](50) NULL,
			[universidad][varchar](255) NULL,
			[fecha_nacimiento][varchar](50) NULL,
			[ciudad_nacimiento][varchar](255) NULL,
			[career_AST][varchar](10) NULL,
			[career_FG%][varchar](10) NULL,
			[career_FG3%][varchar](10) NULL,
			[career_FT%][varchar](10) NULL,
			[career_G][varchar](10)NULL,
			[career_PER][varchar](10) NULL,
			[career_PTS][varchar](10) NULL,
			[career_TRB][varchar](10) NULL,
			[career_WS][varchar](10) NULL,
			[career_eFG%][varchar](10) NULL
) ON [PRIMARY]